{
 "title": "Food Delivery Logs",
 "tags": [
  "food-delivery",
  "logs"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "ERROR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"food-delivery-observability\",service=\"api\"} |= \"\\\"level\\\":\\\"error\\\"\""
    }
   ]
  },
  {
   "title": "WARN",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{project=\"food-delivery-observability\",service=\"api\"} |= \"\\\"level\\\":\\\"warn\\\"\""
    }
   ]
  },
  {
   "title": "POST /orders",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{project=\"food-delivery-observability\",service=\"api\"} |= \"\\\"method\\\":\\\"POST\\\"\" |= \"\\\"endpoint\\\":\\\"/orders\\\"\""
    }
   ]
  },
  {
   "title": "Validation Failures",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{project=\"food-delivery-observability\",service=\"api\"} |= \"Validation failure\""
    }
   ]
  }
 ]
}